apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.app.prefix }}-app
  name: {{ .Values.app.prefix }}-app
  namespace: {{ .Values.app.namespace }}
spec:
  type: NodePort
  ports:
  - name: {{ .Values.service.authproxy.name }}
    port: {{ .Values.service.authproxy.port }}
    targetPort: {{ .Values.service.authproxy.targetPort }}
  - name: {{ .Values.service.camunda.name }}
    port: {{ .Values.service.camunda.port }}
    targetPort: {{ .Values.service.camunda.targetPort }}
  - name: {{ .Values.service.security.name }}
    port: {{ .Values.service.security.port }}
    targetPort: {{ .Values.service.security.targetPort }}
  - name: {{ .Values.service.admin.name }}
    port: {{ .Values.service.admin.port }}
    targetPort: {{ .Values.service.admin.targetPort }}
  - name: {{ .Values.service.systementry.name }}
    port: {{ .Values.service.systementry.port }}
    targetPort: {{ .Values.service.systementry.targetPort }}

  - name: {{ .Values.service.foodmanager.name }}
    port: {{ .Values.service.foodmanager.port }}
    targetPort: {{ .Values.service.foodmanager.targetPort }}

  - name: {{ .Values.service.personmanager.name }}
    port: {{ .Values.service.personmanager.port }}
    targetPort: {{ .Values.service.personmanager.targetPort }}

  - name: {{ .Values.service.nutrition.name }}
    port: {{ .Values.service.nutrition.port }}
    targetPort: {{ .Values.service.nutrition.targetPort }}

  - name: {{ .Values.service.medicationmanager.name }}
    port: {{ .Values.service.medicationmanager.port }}
    targetPort: {{ .Values.service.medicationmanager.targetPort }}

  - name: {{ .Values.service.prescriptionmanager.name }}
    port: {{ .Values.service.prescriptionmanager.port }}
    targetPort: {{ .Values.service.prescriptionmanager.targetPort }}

  - name: {{ .Values.service.workout.name }}
    port: {{ .Values.service.workout.port }}
    targetPort: {{ .Values.service.workout.targetPort }}

  - name: {{ .Values.service.sleeptrack.name }}
    port: {{ .Values.service.sleeptrack.port }}
    targetPort: {{ .Values.service.sleeptrack.targetPort }}

  selector:
    name: {{ .Values.app.prefix }}-app